services:
  web:
    build: ./backend
    container_name: django-backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./backend/django-emqx:/app/django-emqx  # mount your local editable app
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/certs:/app/certs
    networks:
      - backend
    ports:
      - "8000:8000"
    depends_on:
      - emqx

  emqx:
    image: emqx/emqx:latest
    container_name: emqx_broker
    restart: always
    env_file:
      - .env
    networks:
      - backend
    ports:
      - "1883:1883" # MQTT Port
      - "8083:8083" # WebSocket Port
      - "8084:8084"  # Secure WebSocket Port
      - "8883:8883" # Secure MQTT Port
      - "18083:18083" # Dashboard Port
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./emqx/certs:/etc/emqx/certs

networks:
  backend:
    driver: bridge