services:
  web:
    build: ./backend
    container_name: django_backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./emqx/etc/default_api_key.conf:/app/backend/default_api_key.conf
      - ./backend/staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - emqx

  emqx:
    image: emqx/emqx:latest
    container_name: emqx_broker
    restart: always
    env_file:
      - .env
    ports:
      - "1883:1883"  # MQTT Port
      - "8083:8083"  # WebSocket Port
      - "8084:8084"  # Secure WebSocket Port
      - "18083:18083" # Dashboard Port
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./emqx/etc/default_api_key.conf:/opt/emqx/etc/default_api_key.conf