services:
  web:
    build: ./backend
    container_name: django_backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./backend/staticfiles:/app/staticfiles
      - ./certs/ca.crt:/app/certs/ca.crt
    ports:
      - "8000:8000"
    depends_on:
      - emqx

  emqx:
    image: emqx/emqx:latest
    container_name: emqx_broker
    restart: always
    env_file:
      - .env
    ports:
      - "8084:8084"  # Secure WebSocket Port
      - "18083:18083" # Dashboard Port
      - "8883:8883" # Secure MQTT Port
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./emqx/certs:/etc/emqx/certs
